services:
  client:
    build: ./FinalProject
    stdin_open: true
    tty: true 
    depends_on:
      - db
      - pgadmin
  db:
    image: postgres:latest
    ports:
      - "5433:5432" # Host machine <-- Container.
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password!
      - POSTGRES_DB=database
      - PGPORT=5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    depends_on:
      - db
