services:
  client:
    build: ./FinalProject
    stdin_open: true
    tty: true 
    depends_on:
      - db
  db:
    ports:
      - 1433:1433
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
