services:
  client:
    build: ./FinalProject
    stdin_open: true
    tty: true 
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432" # Host machine <-- Container.
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password!
      - POSTGRES_DB=database
      - PGPORT=5432
        
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
