services:
  client:
    build: ./FinalProject
    stdin_open: true
    tty: true 
    depends_on:
      - db
  db:
    ports:
      - 1433:1433
    expose:
      - 1433
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="yourStrong(!)Password"
